const mongoose = require('mongoose');

// ✅ Hardcode MongoDB URI (tạm thời)
const MONGODB_URI = 'mongodb://127.0.0.1:27017/foodecom';

// Product Schema
const ProductSchema = new mongoose.Schema({
  name: { type: String, required: true },
  description: { type: String, required: true },
  price: { type: Number, required: true },
  originalPrice: { type: Number },
  discount: { type: Number, default: 0 },
  image: { type: String, required: true },
  category: {
    type: String,
    required: true,
    enum: ['pizza', 'burger', 'sushi', 'pasta', 'salad', 'dessert', 'drinks'],
  },
  rating: { type: Number, default: 0 },
  reviews: { type: Number, default: 0 },
  isVegetarian: { type: Boolean, default: false },
  isSpicy: { type: Boolean, default: false },
  isPopular: { type: Boolean, default: false },
  isNew: { type: Boolean, default: false },
  stock: { type: Number, default: 0 },
}, { timestamps: true });

const Product = mongoose.models.Product || mongoose.model('Product', ProductSchema);

// Data sản phẩm
const productData = [
  // PIZZA 🍕
  {
    name: "Margherita Pizza",
    description: "Classic Italian pizza with fresh mozzarella, tomatoes, and basil",
    price: 12.99,
    originalPrice: 15.99,
    discount: 19,
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800",
    category: "pizza",
    rating: 4.8,
    reviews: 234,
    isVegetarian: true,
    isSpicy: false,
    isPopular: true,
    isNew: false,
    stock: 50,
  },
  {
    name: "Pepperoni Pizza",
    description: "Loaded with pepperoni, mozzarella cheese and Italian herbs",
    price: 14.99,
    originalPrice: 17.99,
    discount: 17,
    image: "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=800",
    category: "pizza",
    rating: 4.9,
    reviews: 456,
    isVegetarian: false,
    isSpicy: false,
    isPopular: true,
    isNew: false,
    stock: 45,
  },
  {
    name: "BBQ Chicken Pizza",
    description: "Grilled chicken, BBQ sauce, red onions, and cilantro",
    price: 16.99,
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800",
    category: "pizza",
    rating: 4.7,
    reviews: 189,
    isVegetarian: false,
    isSpicy: true,
    isPopular: false,
    isNew: true,
    stock: 30,
  },
  {
    name: "Vegetarian Supreme",
    description: "Bell peppers, mushrooms, olives, onions, and tomatoes",
    price: 13.99,
    image: "https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?w=800",
    category: "pizza",
    rating: 4.6,
    reviews: 167,
    isVegetarian: true,
    isSpicy: false,
    isPopular: false,
    isNew: false,
    stock: 40,
  },

  // BURGERS 🍔
  {
    name: "Classic Cheeseburger",
    description: "Juicy beef patty with cheddar cheese, lettuce, tomato, and special sauce",
    price: 9.99,
    originalPrice: 12.99,
    discount: 23,
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800",
    category: "burger",
    rating: 4.8,
    reviews: 567,
    isVegetarian: false,
    isSpicy: false,
    isPopular: true,
    isNew: false,
    stock: 60,
  },
  {
    name: "Bacon Deluxe Burger",
    description: "Double beef patty, crispy bacon, cheese, and caramelized onions",
    price: 13.99,
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=800",
    category: "burger",
    rating: 4.9,
    reviews: 423,
    isVegetarian: false,
    isSpicy: false,
    isPopular: true,
    isNew: false,
    stock: 35,
  },
  {
    name: "Spicy Chicken Burger",
    description: "Crispy fried chicken with spicy mayo, jalapeños, and coleslaw",
    price: 11.99,
    image: "https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=800",
    category: "burger",
    rating: 4.7,
    reviews: 289,
    isVegetarian: false,
    isSpicy: true,
    isPopular: false,
    isNew: true,
    stock: 42,
  },
  {
    name: "Veggie Burger",
    description: "Plant-based patty with avocado, sprouts, and chipotle aioli",
    price: 10.99,
    image: "https://images.unsplash.com/photo-1520072959219-c595dc870360?w=800",
    category: "burger",
    rating: 4.5,
    reviews: 156,
    isVegetarian: true,
    isSpicy: false,
    isPopular: false,
    isNew: true,
    stock: 38,
  },

  // SUSHI 🍣
  {
    name: "California Roll",
    description: "Crab, avocado, cucumber wrapped in rice and seaweed",
    price: 8.99,
    image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800",
    category: "sushi",
    rating: 4.7,
    reviews: 234,
    isVegetarian: false,
    isSpicy: false,
    isPopular: true,
    isNew: false,
    stock: 55,
  },
  {
    name: "Spicy Tuna Roll",
    description: "Fresh tuna with spicy mayo and cucumber",
    price: 11.99,
    originalPrice: 13.99,
    discount: 14,
    image: "https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?w=800",
    category: "sushi",
    rating: 4.8,
    reviews: 345,
    isVegetarian: false,
    isSpicy: true,
    isPopular: true,
    isNew: false,
    stock: 48,
  },
  {
    name: "Dragon Roll",
    description: "Eel, cucumber topped with avocado and eel sauce",
    price: 14.99,
    image: "https://images.unsplash.com/photo-1611143669185-af224c5e3252?w=800",
    category: "sushi",
    rating: 4.9,
    reviews: 189,
    isVegetarian: false,
    isSpicy: false,
    isPopular: true,
    isNew: false,
    stock: 32,
  },
  {
    name: "Vegetable Roll",
    description: "Cucumber, avocado, carrot, and asparagus",
    price: 7.99,
    image: "https://images.unsplash.com/photo-1583623025817-d180a2221d0a?w=800",
    category: "sushi",
    rating: 4.4,
    reviews: 123,
    isVegetarian: true,
    isSpicy: false,
    isPopular: false,
    isNew: false,
    stock: 60,
  },

  // PASTA 🍝
  {
    name: "Spaghetti Carbonara",
    description: "Creamy pasta with bacon, egg, and parmesan cheese",
    price: 13.99,
    image: "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800",
    category: "pasta",
    rating: 4.8,
    reviews: 278,
    isVegetarian: false,
    isSpicy: false,
    isPopular: true,
    isNew: false,
    stock: 44,
  },
  {
    name: "Penne Arrabbiata",
    description: "Spicy tomato sauce with garlic and red chili peppers",
    price: 11.99,
    originalPrice: 14.99,
    discount: 20,
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800",
    category: "pasta",
    rating: 4.6,
    reviews: 167,
    isVegetarian: true,
    isSpicy: true,
    isPopular: false,
    isNew: false,
    stock: 52,
  },
  {
    name: "Fettuccine Alfredo",
    description: "Rich and creamy parmesan sauce with fettuccine pasta",
    price: 12.99,
    image: "https://images.unsplash.com/photo-1645112411341-6c4fd023714a?w=800",
    category: "pasta",
    rating: 4.7,
    reviews: 234,
    isVegetarian: true,
    isSpicy: false,
    isPopular: true,
    isNew: false,
    stock: 38,
  },
  {
    name: "Seafood Linguine",
    description: "Fresh shrimp, mussels, and clams in white wine sauce",
    price: 17.99,
    image: "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=800",
    category: "pasta",
    rating: 4.9,
    reviews: 145,
    isVegetarian: false,
    isSpicy: false,
    isPopular: false,
    isNew: true,
    stock: 28,
  },

  // SALADS 🥗
  {
    name: "Caesar Salad",
    description: "Romaine lettuce, croutons, parmesan, and Caesar dressing",
    price: 8.99,
    image: "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800",
    category: "salad",
    rating: 4.5,
    reviews: 189,
    isVegetarian: true,
    isSpicy: false,
    isPopular: true,
    isNew: false,
    stock: 65,
  },
  {
    name: "Greek Salad",
    description: "Tomatoes, cucumber, olives, feta cheese, and olive oil",
    price: 9.99,
    image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800",
    category: "salad",
    rating: 4.6,
    reviews: 156,
    isVegetarian: true,
    isSpicy: false,
    isPopular: false,
    isNew: false,
    stock: 58,
  },
  {
    name: "Grilled Chicken Salad",
    description: "Mixed greens, grilled chicken, cherry tomatoes, and balsamic",
    price: 11.99,
    originalPrice: 13.99,
    discount: 14,
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800",
    category: "salad",
    rating: 4.7,
    reviews: 223,
    isVegetarian: false,
    isSpicy: false,
    isPopular: true,
    isNew: false,
    stock: 42,
  },

  // DESSERTS 🍰
  {
    name: "Chocolate Lava Cake",
    description: "Warm chocolate cake with molten center, served with vanilla ice cream",
    price: 7.99,
    image: "https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=800",
    category: "dessert",
    rating: 4.9,
    reviews: 456,
    isVegetarian: true,
    isSpicy: false,
    isPopular: true,
    isNew: false,
    stock: 35,
  },
  {
    name: "New York Cheesecake",
    description: "Creamy cheesecake with graham cracker crust and berry compote",
    price: 6.99,
    image: "https://images.unsplash.com/photo-1533134486753-c833f0ed4866?w=800",
    category: "dessert",
    rating: 4.8,
    reviews: 378,
    isVegetarian: true,
    isSpicy: false,
    isPopular: true,
    isNew: false,
    stock: 48,
  },
  {
    name: "Tiramisu",
    description: "Italian dessert with coffee-soaked ladyfingers and mascarpone",
    price: 8.99,
    originalPrice: 10.99,
    discount: 18,
    image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800",
    category: "dessert",
    rating: 4.7,
    reviews: 267,
    isVegetarian: true,
    isSpicy: false,
    isPopular: false,
    isNew: true,
    stock: 40,
  },
  {
    name: "Crème Brûlée",
    description: "Classic French custard with caramelized sugar topping",
    price: 7.49,
    image: "https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?w=800",
    category: "dessert",
    rating: 4.6,
    reviews: 189,
    isVegetarian: true,
    isSpicy: false,
    isPopular: false,
    isNew: false,
    stock: 32,
  },

  // DRINKS 🥤
  {
    name: "Fresh Orange Juice",
    description: "Freshly squeezed orange juice, no added sugar",
    price: 4.99,
    image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=800",
    category: "drinks",
    rating: 4.5,
    reviews: 234,
    isVegetarian: true,
    isSpicy: false,
    isPopular: true,
    isNew: false,
    stock: 100,
  },
  {
    name: "Iced Coffee",
    description: "Cold brew coffee with ice and milk",
    price: 3.99,
    image: "https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=800",
    category: "drinks",
    rating: 4.7,
    reviews: 456,
    isVegetarian: true,
    isSpicy: false,
    isPopular: true,
    isNew: false,
    stock: 120,
  },
  {
    name: "Mango Smoothie",
    description: "Tropical mango smoothie with yogurt and honey",
    price: 5.99,
    originalPrice: 6.99,
    discount: 14,
    image: "https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=800",
    category: "drinks",
    rating: 4.8,
    reviews: 189,
    isVegetarian: true,
    isSpicy: false,
    isPopular: false,
    isNew: true,
    stock: 85,
  },
  {
    name: "Lemonade",
    description: "Homemade lemonade with fresh lemons and mint",
    price: 3.49,
    image: "https://images.unsplash.com/photo-1523677011781-c91d1bbe2f9d?w=800",
    category: "drinks",
    rating: 4.4,
    reviews: 167,
    isVegetarian: true,
    isSpicy: false,
    isPopular: false,
    isNew: false,
    stock: 95,
  },
];

// Seed function
async function seedDatabase() {
  try {
    console.log('🔄 Connecting to MongoDB...');
    await mongoose.connect(MONGODB_URI);
    console.log('✅ Connected to MongoDB');

    await Product.deleteMany({});
    console.log('🗑️  Cleared existing products');

    const result = await Product.insertMany(productData);
    console.log(`✅ Successfully added ${result.length} products`);

    const categories = await Product.aggregate([
      { $group: { _id: '$category', count: { $sum: 1 } } }
    ]);
    
    console.log('\n📊 Products by category:');
    categories.forEach(cat => {
      console.log(`   ${cat._id}: ${cat.count} items`);
    });

    await mongoose.connection.close();
    console.log('\n✅ Database seeding completed!');
    process.exit(0);

  } catch (error) {
    console.error('❌ Error:', error);
    await mongoose.connection.close();
    process.exit(1);
  }
}

seedDatabase();
